apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: gamechanger
  name: gamechanger
---
apiVersion: v1
kind: Service
metadata:
  name: gamechanger
  namespace: gamechanger
spec:
  ports:
  - port: 80
    targetPort: 4567
  selector:
    app: gamechanger
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: master
    tier: backend
  name: redis
  namespace: gamechanger
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gamechanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - image: redis:latest
        name: master
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamechanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamechanger
      namespace: gamechanger
  template:
    metadata:
      labels:
        app: gamechanger
    spec:
      containers:
      - image: gamechanger
        name: gamechanger
